name: Bump main version

on:
  workflow_run:
    workflows: ['Release and deploy master']
    types: [completed]
    branches:
      - master
    conclusions: [success]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  version_bump:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.0'

      - name: Bump version
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'entimos34@gmail.com'
          npm version patch -m "ci: bump version to %s"
          git push origin HEAD --tags