name: Merge main into master

on:
  workflow_run:
    workflows: ['Build main branch'] # Name of the previous workflow
    types:
      - completed
    branches:
      - main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  merge_main_into_master:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.POKEMON_GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Merge main into master
        run: |
          git fetch origin main
          git checkout master
          git merge origin/main --no-edit
          git push origin master