name: Deployment pipeline

on:
  push:
    branches:
      - master

jobs:
  build_pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '22.4.0'

      - name: Install dependencies 
        run: npm install

      - name: Check style
        run: npm run lint

      - name: Build the app for production
        run: npm run predeploy

  deployment_pipeline:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: build_pipeline

    permissions:
      pages: write
      id-token: write

    environment: # environment created automatically by GitHub
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v1
        with: # location of the coverage artifacts
          path: "./coverage"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2